### ISSUE TITLE
阴阳师防脚本问题

### ISSUE THREAD

**Issue by gwd0715** [877254169/yysHelper#1]
你好，最近我用python也写了一个，发现用pynput或者pymouse 的库会被yys窗口屏蔽click动作，请问该如何突破呢，如何让yys认为这个click不是从script来的而是人为的呢？

**Comment by gwd0715** [comment]
已解决谢谢

**Comment by 877254169** [comment]
不好意思啊，邮件好像被屏蔽了还是怎么了一直没看到，我对python的研究也不是很深，只是想用一下图像识别的库，至于这个click我也是在别人博客看到的，直接拿来用了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"gwd0715"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月25日(星期五) 中午11:03
收件人:&nbsp;"877254169/yysHelper"<yysHelper@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[877254169/yysHelper] 阴阳师防脚本问题 (#1)




你好，最近我用python也写了一个，发现用pynput或者pymouse 的库会被yys窗口屏蔽click动作，请问该如何突破呢，如何让yys认为这个click不是从script来的而是人为的呢？
